# Generated by Django 5.2.8 on 2026-01-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('plafonnee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('imposable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationIRSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(max_length=50, unique=True, verbose_name='Numéro Document')),
                ('nature_impots', models.CharField(default='IMPÔTS SUR LES REVENUS SALARIAUX ET ASSIMILÉS', max_length=255, verbose_name="Nature d'impôts")),
                ('date_declaration', models.DateField(auto_now_add=True)),
                ('total_irsa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_salaire_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nombre_travailleurs_total', models.IntegerField(default=0, verbose_name='1 - Nombre de travailleurs')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='utilisateurs.employeur', verbose_name='Contribuable Déclarant')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='declarations.periodefiscale')),
            ],
            options={
                'unique_together': {('employeur', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='LigneDeclarationIRSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_imposable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('irsa_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='declarations.declarationirsa')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_irsa', to='utilisateurs.employe')),
            ],
            options={
                'unique_together': {('declaration', 'employe')},
            },
        ),
        migrations.CreateModel(
            name='RegimeSpecialIRSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_unitaire_min', models.PositiveIntegerField()),
                ('taux_unitaire_max', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_travailleurs', models.PositiveIntegerField()),
                ('masse_salaire_globale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimes_speciaux', to='declarations.declarationirsa')),
            ],
        ),
        migrations.CreateModel(
            name='SituationFamiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personnes_charge', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations_familiales', to='utilisateurs.employe')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='declarations.lignedeclarationirsa')),
                ('type_deduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='declarations.typededuction')),
            ],
        ),
        migrations.CreateModel(
            name='DetailRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus', to='declarations.lignedeclarationirsa')),
                ('type_revenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='declarations.typerevenu')),
            ],
        ),
    ]
