# Generated by Django 5.2.8 on 2026-01-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodefiscale',
            name='periode_label',
            field=models.CharField(default='MENSUEL', max_length=50),
        ),
    ]
