# Generated by Django 5.2.8 on 2026-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_periodefiscale_periode_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodefiscale',
            name='periode_label',
        ),
        migrations.AddField(
            model_name='periodefiscale',
            name='periode_type',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('bimestriel', 'Bimestriel'), ('trimestriel', 'Trimestriel')], default='mensuel', max_length=20),
        ),
    ]
