# Generated by Django 5.2.8 on 2026-01-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_remove_periodefiscale_periode_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheBareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_fiscale', models.PositiveIntegerField(verbose_name="Année d'application")),
                ('seuil_minimal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='À partir de')),
                ('seuil_maximal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Jusqu'à")),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux (%)')),
                ('somme_a_deduire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('minimum_perception', models.DecimalField(decimal_places=2, default=3000, help_text='Impôt minimum à payer (ex: 3.000 Ar)', max_digits=15)),
            ],
            options={
                'verbose_name': 'Tranche du barème IRSA',
                'ordering': ['annee_fiscale', 'seuil_minimal'],
            },
        ),
        migrations.AddField(
            model_name='declarationirsa',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
    ]
