# Generated by Django 5.2.8 on 2026-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0004_tranchebareme_declarationirsa_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodefiscale',
            name='annee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='periodefiscale',
            unique_together={('annee', 'date_debut', 'date_fin')},
        ),
    ]
