# Generated by Django 5.2.8 on 2026-01-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0005_alter_periodefiscale_annee_and_more'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIRSATemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cnaps', models.CharField(max_length=30)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(blank=True, max_length=20, null=True)),
                ('fonction', models.CharField(blank=True, max_length=150, null=True)),
                ('remuneration_brute', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avantages_nature', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_sante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenu_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impot_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personnes_charge', models.IntegerField(default=0)),
                ('reduction_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impot_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_valide', models.BooleanField(default=False)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateurs.employeur')),
            ],
        ),
    ]
