# Generated by Django 5.2.8 on 2026-01-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0006_importirsatemporaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranchebareme',
            name='somme_a_deduire',
        ),
    ]
