# Generated by Django 5.2.8 on 2026-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0007_remove_tranchebareme_somme_a_deduire'),
    ]

    operations = [
        migrations.AddField(
            model_name='importirsatemporaire',
            name='impot_net_theo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IRSA calculé par le système', max_digits=12),
        ),
        migrations.AddField(
            model_name='importirsatemporaire',
            name='revenu_net_theo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='RNI calculé par le système', max_digits=12),
        ),
    ]
