# Generated by Django 5.2.8 on 2026-01-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0008_importirsatemporaire_impot_net_theo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importirsatemporaire',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRME', 'Confirmé')], default='BROUILLON', max_length=20),
        ),
    ]
