# Generated by Django 5.2.8 on 2026-01-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0009_importirsatemporaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importirsatemporaire',
            name='statut',
            field=models.CharField(choices=[('IMPORTE', 'Importé'), ('BROUILLON', 'Brouillon'), ('CONFIRME', 'Confirmé')], default='BROUILLON', max_length=20),
        ),
    ]
