# Generated by Django 5.2.8 on 2026-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0010_alter_importirsatemporaire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedeclarationirsa',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignedeclarationirsa',
            name='est_lu',
            field=models.BooleanField(default=False),
        ),
    ]
