# Generated by Django 5.2.8 on 2026-02-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0011_lignedeclarationirsa_date_lecture_and_more'),
        ('utilisateurs', '0004_employe_nif_individuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodefiscale',
            name='employeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodes_fiscales', to='utilisateurs.employeur'),
        ),
    ]
