# Generated by Django 5.2.8 on 2026-02-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0012_periodefiscale_employeur'),
        ('utilisateurs', '0004_employe_nif_individuel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodefiscale',
            unique_together={('annee', 'date_debut', 'date_fin', 'employeur')},
        ),
    ]
