# Generated by Django 5.2.8 on 2026-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0013_alter_periodefiscale_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationirsa',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('valide', 'Validé'), ('archive', 'archivé')], default='brouillon', max_length=20),
        ),
    ]
