# Generated by Django 5.2.8 on 2026-01-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={},
        ),
    ]
