# Generated by Django 5.2.8 on 2026-02-03 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_usercustom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
