# Generated by Django 5.2.8 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nif_individuel',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
