# Generated by Django 5.2.8 on 2026-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NifAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NifEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(editable=False, max_length=15, unique=True)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base NIF Employe',
                'verbose_name_plural': 'Base NIF Employes',
            },
        ),
    ]
