# Generated by Django 5.2.8 on 2026-02-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NifAPI', '0002_nifemploye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nifemploye',
            name='nom_prenom',
        ),
        migrations.AddField(
            model_name='nifemploye',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
