# Generated by Django 5.2.8 on 2026-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NifAPI', '0003_remove_nifemploye_nom_prenom_nifemploye_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifemploye',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
